---
title: "Perception of groove: Validation - No Interaction"
author: "Ruta Slivkaite"
date: "2024"
output: html_document
---



## Loading libraries
```{r}
library(rjags)
library(coda)
library(jsonlite)

```

## Loading data
```{r, echo=FALSE}

# Set working directory
setwd("C:/Users/Ruta/Documents/Rutos SmuTkes/CogSci/Master/Decision making")

# Load data
MRAnalysis <- read.csv("Data/Data_MRAnalysis_OSF.csv") # all variables for the analysis

Groove_Ratings <- read.csv("Data/Groove_Ratings_Data_OSF.csv") # groove ratings (objective)


# Load Metadata
json_data_Groove_Ratings <- fromJSON("Data/a4ed8-datacite.json") # all variables for the analysis

json_data_MRAnalysis <- fromJSON("Data/cnmv5-datacite.json") # groove ratings


```

```{r}


# Loading full dataset
MRAnalysis <- read.csv("C:/Users/Ruta/Documents/Rutos SmuTkes/CogSci/Master/Decision making/Data/Data_MRAnalysis_OSF.csv") # all variables for the analysis

Groove_Ratings <- read.csv("C:/Users/Ruta/Documents/Rutos SmuTkes/CogSci/Master/Decision making/Data/Groove_Ratings_Data_OSF.csv") # groove ratings (objective)

########### Preparing MSI and DSI ###########

# Extracting necessary columns
# GOLD_MSI_MusicalSophistication, GOLD_DSI_DanceTraining
MSI_val <- MRAnalysis[c("Participants", "GOLD_MSI_MusicalSophistication")]
DSI_val <- MRAnalysis[c("Participants", "GOLD_DSI_DanceTraining")]
# arrange by Participant in a descending order and get MSI and DSI
MSI_sorted <- MSI_val %>% arrange(Participants)
DSI_sorted <- DSI_val %>% arrange(Participants)


# Convert from long to wide format
# MSI
wide_MSI <- MSI_sorted %>% 
  pivot_wider(names_from = Participants, values_from = c("GOLD_MSI_MusicalSophistication"))
MSI_val <- wide_MSI[rep(1, 20), ]
# DSI
wide_DSI <- DSI_sorted %>% 
  pivot_wider(names_from = Participants, values_from = c("GOLD_DSI_DanceTraining"))
DSI_val <- wide_DSI[rep(1, 20), ]

# Transform it into a matrix
MSI_val_matrix <- as.matrix(MSI_val)
DSI_val_matrix <- as.matrix(DSI_val)

# Normalize MSI and DSI
##### MSI
# Calculating the mean and standard deviation of the matrix
mean_MSI_val <- mean(MSI_val_matrix)
sd_MSI_val <- sd(MSI_val_matrix)
# Standardizing the matrix
MSI_val_matrix <- (MSI_val_matrix - mean_MSI_val) / sd_MSI_val

###### DSI
# Calculating the mean and standard deviation of the matrix
mean_DSI_val <- mean(DSI_val_matrix)
sd_DSI_val <- sd(DSI_val_matrix)
# Standardizing the matrix
DSI_val_matrix <- (DSI_val_matrix - mean_DSI_val) / sd_DSI_val





########### Preparing Groove, Familiarity, Pleasure ratings ###########

# Loading participant ratings for each song
Participant_Song_Ratings <- read.csv("C:/Users/Ruta/Documents/Rutos SmuTkes/CogSci/Master/Decision making/Data/Participant_Song_Ratings.csv", header = TRUE, sep = ";")

# Separate like, groove, familiarity. Reverse it so each song is in the rows (20 rows) and every participant rating is in the columns

# Number of songs
num_songs <- 20

# Create indices for each rating type
groove_indices <- seq(1, num_songs * 3, by = 3)
like_indices <- seq(2, num_songs * 3, by = 3)
familiar_indices <- seq(3, num_songs * 3, by = 3)

# Extract columns for each rating type
groove_indices <- grep("\\.groove$", names(Participant_Song_Ratings))
like_indices <- grep("\\.like$", names(Participant_Song_Ratings))
familiar_indices <- grep("\\.familiar$", names(Participant_Song_Ratings))

participant_id_col <- 1
# Extract columns for each rating type
groove_df<- Participant_Song_Ratings[, c(participant_id_col, groove_indices)]
like_df <- Participant_Song_Ratings[, c(participant_id_col, like_indices)]
familiar_df <- Participant_Song_Ratings[, c(participant_id_col, familiar_indices)]


####### Familiarity #######
## Create a matrix where each row is a song and each column is a value how familiar participant is with that song
# Transpose the data
transposed_familiar <- t(familiar_df)
# Convert back to data frame 
familiar_df <- as.data.frame(transposed_familiar)
# Set the names of the columns to be the values in the first row
colnames(familiar_df) <- as.character(familiar_df[1, ])
# Remove the first row 
familiar_df <- familiar_df[-1, ]
# Transform it into a matrix
familiar_matrix <- as.matrix(familiar_df)


####### Pleasure  #######
# Transpose the data
transposed_like <- t(like_df)
# Convert back to data frame 
like_df <- as.data.frame(transposed_like)
# Set the names of the columns to be the values in the first row
colnames(like_df) <- as.character(like_df[1, ])
# Remove the first row 
like_df <- like_df[-1, ]
# Transform it into a matrix
like_matrix <- as.matrix(like_df)


####### Groove  #######
# Transpose the data
transposed_groove <- t(groove_df)
# Convert back to data frame 
groove_df <- as.data.frame(transposed_groove)
# Set the names of the columns to be the values in the first row
colnames(groove_df) <- as.character(groove_df[1, ])
# Remove the first row 
groove_df <- groove_df[-1, ]
# Transform it into a matrix
groove_matrix <- as.matrix(groove_df)


####### Objective groove ratings #######

preset_objGrooveRatings <- c(108.7, 105.9, 105.1, 102.5, 102.4, 101.6, 101.1, 98.7, 97.4, 96.9, 38.7, 38.5, 38.1, 36.5, 35.2, 34.8, 32.6, 32.1, 30.9, 29.3)
min_rating <- min(preset_objGrooveRatings)
max_rating <- max(preset_objGrooveRatings)
scaled_objGrooveRatings <- (preset_objGrooveRatings - min_rating) / (max_rating - min_rating)

N_songs <- 20  # Total number of songs
grooveLevel <- c(rep(1, N_songs/2), rep(0, N_songs/2))
# Organize the objGrooveRating in the same order as grooveLevel
objGrooveRating <- scaled_objGrooveRatings[order(match(grooveLevel, sample(c(0, 1), N, replace = TRUE)))]

```



```{r}


song_types <- rep(c("High Groove", "Low Groove"), each = 10)  
participants <- paste("Participant", 1:ncol(like_matrix), sep = "")
participants

# Convert the matrix to a data frame
like_data_df <- as.data.frame(like_matrix, row.names = song_types)

# Reshape the data to long format
library(reshape2)
df_long <- melt(like_data_df, variable.name = "Participant", value.name = "Rating")
df_long$SongType <- rep(song_types, ncol(like_matrix))


# Combined Violin plot for all participants
p_violin <- ggplot(df_long, aes(x = SongType, y = Rating, fill = SongType)) +
  geom_violin() +
  labs(title = "Combined Distribution of Pleasure Ratings for High and Low Groove Songs", 
       x = "Song Type", 
       y = "Rating") +
  theme_classic()
ggsave("Violin_plot_highVSlow.png", plot = p_violin, width = 10, height = 5)


# Ratings for high anf low groove songs
p_ratings <- ggplot(df_long, aes(x = Participant, y = Rating, color = SongType)) +
    geom_point() +
    labs(title = "All Ratings for High and Low Groove Songs", 
         x = "Participant", 
         y = "Rating") +
    scale_color_manual(values = c("High Groove" = "blue", "Low Groove" = "red")) +
    theme_minimal() +
    theme(axis.text.x = element_blank(), axis.ticks.x = element_blank())

```




#### Running the model
```{r}

set.seed(88)
N <- 20  # Number of songs
P <- 124  # Number of participants


# Split the matrix into two matrices, each with 10 rows
#rating_high <- like_matrix[1:10, ]
#rating_low <- like_matrix[11:20, ]

################### Prepare data for JAGS ###################
data_jags_val <- list(
  N = N,
  P = P,
  rating = like_matrix, # using like variable
  objGrooveRating = objGrooveRating,
  MSI = MSI_val_matrix,
  DSI = DSI_val_matrix,
  Familiarity = familiar_matrix,
  grooveLevel = grooveLevel,
  participant_effect = participant_effect
  
)

# Load the model
model_file = "Models/Groove_model_No_interaction.txt"
jags_model_val = jags.model(file = model_file, data = data_jags_val, n.chains = 3, n.adapt = 1000)

# Burn-in period
update(jags_model_val, 1000)

# Sample from the posterior
samples_val_2 = coda.samples(jags_model_val, variable.names = c("gamma0", "gamma1","beta0_high", "beta1_high", "beta2_high", "beta3_high", "beta5_high", "beta0_low", "beta1_low", "beta2_low", "beta3_low", "beta4_low", "tau_participant_effect", "tau_fam", "rating_high", "rating_low", "fit", "fit_new"), n.iter = 8000)


# Save the MCMC samples to a file
save(samples_val_2, file = "mcmc_samples_validation_2.RData")
```

```{r}

# View the results
print(summary(samples_val_2))

exp_results <- exp(summary(samples_val_2)$statistics[, "Mean"])
print(exp_results)

exp_results <- exp(summary(samples_val_2)$statistics[, "SD"])
print(exp_results)

```




```{r}

# Create trace plots
traceplot(samples_val_2)



```

```{r, save trace plots}

library(ggplot2)
library(coda)
library(dplyr)
library(tidyr)

# Extract data from the mcmc.list object
chain_list <- lapply(1:length(samples_val_2), function(x) {
  as.data.frame(samples_val_2[[x]])
})

# Add chain and iteration information
for (i in 1:length(chain_list)) {
  chain_list[[i]]$Chain <- i
  chain_list[[i]]$Iteration <- 1:nrow(chain_list[[i]])
}

# Combine all chains into one data frame
df_samples <- bind_rows(chain_list)

# Convert to long format suitable for ggplot
long_samples <- gather(df_samples, key = "Parameter", value = "Value", -Chain, -Iteration)

# Create the plot
p <- ggplot(long_samples, aes(x = Iteration, y = Value, color = as.factor(Chain))) +
    geom_line() +
    facet_wrap(~ Parameter, scales = "free")

# Save the plot
ggsave("traceplot_validation.png", plot = p, width = 10, height = 8)







```






